version: "3"
services:
  #Nginx Service
  stagingNginx:
    image: nginx:alpine
    container_name: stagingNginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./laravel:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - hilton_app-network
      
#Docker Networks
networks:
  hilton_app-network:
    external: true

#Volumes
volumes:
  stagingDBData:
    driver: local
